apiVersion: v1
kind: Service
metadata:
  name: w1sdf
  namespace: namespace-workflow-1751767255192
  labels:
    app.kubernetes.io/name: w1sdf
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: w1sdf
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000